<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0-windows10.0.22000.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <!-- These normally come from $(UseWindowsForms) when $(ImplicitUsings) is enabled -->
  <ItemGroup>
    <Using Include="System.Drawing" />
    <Using Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
