// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using VisualStylesModeDemo.Controls;

namespace VisualStylesModeDemo.Views;

partial class CashRegisterView
{
    /// <summary>
    ///  Required designer variable.
    /// </summary>
    private System.ComponentModel.IContainer components = null;

    /// <summary>
    ///  Clean up any resources being used.
    /// </summary>
    /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    #region Component Designer generated code

    /// <summary>
    ///  Required method for Designer support - do not modify
    ///  the contents of this method with the code editor.
    /// </summary>
    private void InitializeComponent()
    {
        _rootLayout = new TableLayoutPanel();
        _registerLayout = new TableLayoutPanel();
        _display = new SevenSegmentDisplay();
        _keyBodyLayout = new TableLayoutPanel();
        _denominationGrid = new TableLayoutPanel();
        _thousandsHeaderLabel = new Label();
        _hundredsHeaderLabel = new Label();
        _tensHeaderLabel = new Label();
        _onesHeaderLabel = new Label();
        _tenthsHeaderLabel = new Label();
        _hundredthsHeaderLabel = new Label();
        _thousands9Button = new CashRegisterKeyButton();
        _thousands8Button = new CashRegisterKeyButton();
        _thousands7Button = new CashRegisterKeyButton();
        _thousands6Button = new CashRegisterKeyButton();
        _thousands5Button = new CashRegisterKeyButton();
        _thousands4Button = new CashRegisterKeyButton();
        _thousands3Button = new CashRegisterKeyButton();
        _thousands2Button = new CashRegisterKeyButton();
        _thousands1Button = new CashRegisterKeyButton();
        _hundreds9Button = new CashRegisterKeyButton();
        _hundreds8Button = new CashRegisterKeyButton();
        _hundreds7Button = new CashRegisterKeyButton();
        _hundreds6Button = new CashRegisterKeyButton();
        _hundreds5Button = new CashRegisterKeyButton();
        _hundreds4Button = new CashRegisterKeyButton();
        _hundreds3Button = new CashRegisterKeyButton();
        _hundreds2Button = new CashRegisterKeyButton();
        _hundreds1Button = new CashRegisterKeyButton();
        _tens9Button = new CashRegisterKeyButton();
        _tens8Button = new CashRegisterKeyButton();
        _tens7Button = new CashRegisterKeyButton();
        _tens6Button = new CashRegisterKeyButton();
        _tens5Button = new CashRegisterKeyButton();
        _tens4Button = new CashRegisterKeyButton();
        _tens3Button = new CashRegisterKeyButton();
        _tens2Button = new CashRegisterKeyButton();
        _tens1Button = new CashRegisterKeyButton();
        _ones9Button = new CashRegisterKeyButton();
        _ones8Button = new CashRegisterKeyButton();
        _ones7Button = new CashRegisterKeyButton();
        _ones6Button = new CashRegisterKeyButton();
        _ones5Button = new CashRegisterKeyButton();
        _ones4Button = new CashRegisterKeyButton();
        _ones3Button = new CashRegisterKeyButton();
        _ones2Button = new CashRegisterKeyButton();
        _ones1Button = new CashRegisterKeyButton();
        _tenths9Button = new CashRegisterKeyButton();
        _tenths8Button = new CashRegisterKeyButton();
        _tenths7Button = new CashRegisterKeyButton();
        _tenths6Button = new CashRegisterKeyButton();
        _tenths5Button = new CashRegisterKeyButton();
        _tenths4Button = new CashRegisterKeyButton();
        _tenths3Button = new CashRegisterKeyButton();
        _tenths2Button = new CashRegisterKeyButton();
        _tenths1Button = new CashRegisterKeyButton();
        _hundredths9Button = new CashRegisterKeyButton();
        _hundredths8Button = new CashRegisterKeyButton();
        _hundredths7Button = new CashRegisterKeyButton();
        _hundredths6Button = new CashRegisterKeyButton();
        _hundredths5Button = new CashRegisterKeyButton();
        _hundredths4Button = new CashRegisterKeyButton();
        _hundredths3Button = new CashRegisterKeyButton();
        _hundredths2Button = new CashRegisterKeyButton();
        _hundredths1Button = new CashRegisterKeyButton();
        _departmentAndActionLayout = new TableLayoutPanel();
        _departmentGrid = new TableLayoutPanel();
        _department01Button = new CashRegisterKeyButton();
        _department02Button = new CashRegisterKeyButton();
        _department03Button = new CashRegisterKeyButton();
        _department04Button = new CashRegisterKeyButton();
        _department05Button = new CashRegisterKeyButton();
        _department06Button = new CashRegisterKeyButton();
        _department07Button = new CashRegisterKeyButton();
        _department08Button = new CashRegisterKeyButton();
        _department09Button = new CashRegisterKeyButton();
        _department10Button = new CashRegisterKeyButton();
        _department11Button = new CashRegisterKeyButton();
        _department12Button = new CashRegisterKeyButton();
        _department13Button = new CashRegisterKeyButton();
        _department14Button = new CashRegisterKeyButton();
        _department15Button = new CashRegisterKeyButton();
        _department16Button = new CashRegisterKeyButton();
        _department17Button = new CashRegisterKeyButton();
        _department18Button = new CashRegisterKeyButton();
        _department19Button = new CashRegisterKeyButton();
        _department20Button = new CashRegisterKeyButton();
        _actionGrid = new TableLayoutPanel();
        _taxButton = new CashRegisterKeyButton();
        _voidButton = new CashRegisterKeyButton();
        _subtotalButton = new CashRegisterKeyButton();
        _totalButton = new CashRegisterKeyButton();
        _receiptGroupBox = new GroupBox();
        _receiptTextBox = new RichTextBox();
        _rootLayout.SuspendLayout();
        _registerLayout.SuspendLayout();
        _keyBodyLayout.SuspendLayout();
        _denominationGrid.SuspendLayout();
        _departmentAndActionLayout.SuspendLayout();
        _departmentGrid.SuspendLayout();
        _actionGrid.SuspendLayout();
        _receiptGroupBox.SuspendLayout();
        SuspendLayout();
        //
        // _rootLayout
        //
        _rootLayout.ColumnCount = 2;
        _rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 74F));
        _rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 26F));
        _rootLayout.Controls.Add(_registerLayout, 0, 0);
        _rootLayout.Controls.Add(_receiptGroupBox, 1, 0);
        _rootLayout.Location = new Point(0, 0);
        _rootLayout.Name = "_rootLayout";
        _rootLayout.Padding = new Padding(8);
        _rootLayout.RowCount = 1;
        _rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        _rootLayout.Size = new Size(1200, 820);
        _rootLayout.TabIndex = 0;
        //
        // _registerLayout
        //
        _registerLayout.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _registerLayout.ColumnCount = 1;
        _registerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        _registerLayout.Controls.Add(_display, 0, 0);
        _registerLayout.Controls.Add(_keyBodyLayout, 0, 1);
        _registerLayout.Location = new Point(11, 11);
        _registerLayout.Name = "_registerLayout";
        _registerLayout.RowCount = 2;
        _registerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 126F));
        _registerLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        _registerLayout.Size = new Size(870, 798);
        _registerLayout.TabIndex = 0;
        //
        // _display
        //
        _display.AccessibleName = "Cash register amount display";
        _display.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _display.Location = new Point(6, 6);
        _display.Margin = new Padding(6);
        _display.Name = "_display";
        _display.Size = new Size(858, 114);
        _display.TabIndex = 0;
        //
        // _keyBodyLayout
        //
        _keyBodyLayout.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _keyBodyLayout.ColumnCount = 2;
        _keyBodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 62F));
        _keyBodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 38F));
        _keyBodyLayout.Controls.Add(_denominationGrid, 0, 0);
        _keyBodyLayout.Controls.Add(_departmentAndActionLayout, 1, 0);
        _keyBodyLayout.Location = new Point(3, 129);
        _keyBodyLayout.Name = "_keyBodyLayout";
        _keyBodyLayout.RowCount = 1;
        _keyBodyLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        _keyBodyLayout.Size = new Size(864, 666);
        _keyBodyLayout.TabIndex = 1;
        //
        // _denominationGrid
        //
        _denominationGrid.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _denominationGrid.ColumnCount = 6;
        _denominationGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.66667F));
        _denominationGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.66667F));
        _denominationGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.66667F));
        _denominationGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.66667F));
        _denominationGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.66667F));
        _denominationGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.66667F));
        _denominationGrid.Controls.Add(_thousandsHeaderLabel, 0, 0);
        _denominationGrid.Controls.Add(_hundredsHeaderLabel, 1, 0);
        _denominationGrid.Controls.Add(_tensHeaderLabel, 2, 0);
        _denominationGrid.Controls.Add(_onesHeaderLabel, 3, 0);
        _denominationGrid.Controls.Add(_tenthsHeaderLabel, 4, 0);
        _denominationGrid.Controls.Add(_hundredthsHeaderLabel, 5, 0);
        _denominationGrid.Controls.Add(_thousands9Button, 0, 1);
        _denominationGrid.Controls.Add(_thousands8Button, 0, 2);
        _denominationGrid.Controls.Add(_thousands7Button, 0, 3);
        _denominationGrid.Controls.Add(_thousands6Button, 0, 4);
        _denominationGrid.Controls.Add(_thousands5Button, 0, 5);
        _denominationGrid.Controls.Add(_thousands4Button, 0, 6);
        _denominationGrid.Controls.Add(_thousands3Button, 0, 7);
        _denominationGrid.Controls.Add(_thousands2Button, 0, 8);
        _denominationGrid.Controls.Add(_thousands1Button, 0, 9);
        _denominationGrid.Controls.Add(_hundreds9Button, 1, 1);
        _denominationGrid.Controls.Add(_hundreds8Button, 1, 2);
        _denominationGrid.Controls.Add(_hundreds7Button, 1, 3);
        _denominationGrid.Controls.Add(_hundreds6Button, 1, 4);
        _denominationGrid.Controls.Add(_hundreds5Button, 1, 5);
        _denominationGrid.Controls.Add(_hundreds4Button, 1, 6);
        _denominationGrid.Controls.Add(_hundreds3Button, 1, 7);
        _denominationGrid.Controls.Add(_hundreds2Button, 1, 8);
        _denominationGrid.Controls.Add(_hundreds1Button, 1, 9);
        _denominationGrid.Controls.Add(_tens9Button, 2, 1);
        _denominationGrid.Controls.Add(_tens8Button, 2, 2);
        _denominationGrid.Controls.Add(_tens7Button, 2, 3);
        _denominationGrid.Controls.Add(_tens6Button, 2, 4);
        _denominationGrid.Controls.Add(_tens5Button, 2, 5);
        _denominationGrid.Controls.Add(_tens4Button, 2, 6);
        _denominationGrid.Controls.Add(_tens3Button, 2, 7);
        _denominationGrid.Controls.Add(_tens2Button, 2, 8);
        _denominationGrid.Controls.Add(_tens1Button, 2, 9);
        _denominationGrid.Controls.Add(_ones9Button, 3, 1);
        _denominationGrid.Controls.Add(_ones8Button, 3, 2);
        _denominationGrid.Controls.Add(_ones7Button, 3, 3);
        _denominationGrid.Controls.Add(_ones6Button, 3, 4);
        _denominationGrid.Controls.Add(_ones5Button, 3, 5);
        _denominationGrid.Controls.Add(_ones4Button, 3, 6);
        _denominationGrid.Controls.Add(_ones3Button, 3, 7);
        _denominationGrid.Controls.Add(_ones2Button, 3, 8);
        _denominationGrid.Controls.Add(_ones1Button, 3, 9);
        _denominationGrid.Controls.Add(_tenths9Button, 4, 1);
        _denominationGrid.Controls.Add(_tenths8Button, 4, 2);
        _denominationGrid.Controls.Add(_tenths7Button, 4, 3);
        _denominationGrid.Controls.Add(_tenths6Button, 4, 4);
        _denominationGrid.Controls.Add(_tenths5Button, 4, 5);
        _denominationGrid.Controls.Add(_tenths4Button, 4, 6);
        _denominationGrid.Controls.Add(_tenths3Button, 4, 7);
        _denominationGrid.Controls.Add(_tenths2Button, 4, 8);
        _denominationGrid.Controls.Add(_tenths1Button, 4, 9);
        _denominationGrid.Controls.Add(_hundredths9Button, 5, 1);
        _denominationGrid.Controls.Add(_hundredths8Button, 5, 2);
        _denominationGrid.Controls.Add(_hundredths7Button, 5, 3);
        _denominationGrid.Controls.Add(_hundredths6Button, 5, 4);
        _denominationGrid.Controls.Add(_hundredths5Button, 5, 5);
        _denominationGrid.Controls.Add(_hundredths4Button, 5, 6);
        _denominationGrid.Controls.Add(_hundredths3Button, 5, 7);
        _denominationGrid.Controls.Add(_hundredths2Button, 5, 8);
        _denominationGrid.Controls.Add(_hundredths1Button, 5, 9);
        _denominationGrid.Location = new Point(3, 3);
        _denominationGrid.MinimumSize = new Size(510, 620);
        _denominationGrid.Name = "_denominationGrid";
        _denominationGrid.RowCount = 10;
        _denominationGrid.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        _denominationGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 11.11111F));
        _denominationGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 11.11111F));
        _denominationGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 11.11111F));
        _denominationGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 11.11111F));
        _denominationGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 11.11111F));
        _denominationGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 11.11111F));
        _denominationGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 11.11111F));
        _denominationGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 11.11111F));
        _denominationGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 11.11111F));
        _denominationGrid.Size = new Size(530, 660);
        _denominationGrid.TabIndex = 0;
        //
        // denomination headers
        //
        _thousandsHeaderLabel.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _thousandsHeaderLabel.AutoSize = true;
        _thousandsHeaderLabel.Name = "_thousandsHeaderLabel";
        _thousandsHeaderLabel.TabIndex = 0;
        _thousandsHeaderLabel.Text = "THOU";
        _thousandsHeaderLabel.TextAlign = ContentAlignment.MiddleCenter;
        _hundredsHeaderLabel.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _hundredsHeaderLabel.AutoSize = true;
        _hundredsHeaderLabel.Name = "_hundredsHeaderLabel";
        _hundredsHeaderLabel.TabIndex = 0;
        _hundredsHeaderLabel.Text = "HUN";
        _hundredsHeaderLabel.TextAlign = ContentAlignment.MiddleCenter;
        _tensHeaderLabel.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _tensHeaderLabel.AutoSize = true;
        _tensHeaderLabel.Name = "_tensHeaderLabel";
        _tensHeaderLabel.TabIndex = 0;
        _tensHeaderLabel.Text = "TENS";
        _tensHeaderLabel.TextAlign = ContentAlignment.MiddleCenter;
        _onesHeaderLabel.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _onesHeaderLabel.AutoSize = true;
        _onesHeaderLabel.Name = "_onesHeaderLabel";
        _onesHeaderLabel.TabIndex = 0;
        _onesHeaderLabel.Text = "ONES";
        _onesHeaderLabel.TextAlign = ContentAlignment.MiddleCenter;
        _tenthsHeaderLabel.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _tenthsHeaderLabel.AutoSize = true;
        _tenthsHeaderLabel.Name = "_tenthsHeaderLabel";
        _tenthsHeaderLabel.TabIndex = 0;
        _tenthsHeaderLabel.Text = "10c";
        _tenthsHeaderLabel.TextAlign = ContentAlignment.MiddleCenter;
        _hundredthsHeaderLabel.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _hundredthsHeaderLabel.AutoSize = true;
        _hundredthsHeaderLabel.Name = "_hundredthsHeaderLabel";
        _hundredthsHeaderLabel.TabIndex = 0;
        _hundredthsHeaderLabel.Text = "1c";
        _hundredthsHeaderLabel.TextAlign = ContentAlignment.MiddleCenter;
        //
        // denomination buttons
        //
        _thousands9Button.Name = "_thousands9Button";
        _thousands9Button.TabIndex = 1;
        _thousands9Button.Text = "9K";
        _thousands9Button.Click += DenominationButton_Click;
        _thousands8Button.Name = "_thousands8Button";
        _thousands8Button.TabIndex = 7;
        _thousands8Button.Text = "8K";
        _thousands8Button.Click += DenominationButton_Click;
        _thousands7Button.Name = "_thousands7Button";
        _thousands7Button.TabIndex = 13;
        _thousands7Button.Text = "7K";
        _thousands7Button.Click += DenominationButton_Click;
        _thousands6Button.Name = "_thousands6Button";
        _thousands6Button.TabIndex = 19;
        _thousands6Button.Text = "6K";
        _thousands6Button.Click += DenominationButton_Click;
        _thousands5Button.Name = "_thousands5Button";
        _thousands5Button.TabIndex = 25;
        _thousands5Button.Text = "5K";
        _thousands5Button.Click += DenominationButton_Click;
        _thousands4Button.Name = "_thousands4Button";
        _thousands4Button.TabIndex = 31;
        _thousands4Button.Text = "4K";
        _thousands4Button.Click += DenominationButton_Click;
        _thousands3Button.Name = "_thousands3Button";
        _thousands3Button.TabIndex = 37;
        _thousands3Button.Text = "3K";
        _thousands3Button.Click += DenominationButton_Click;
        _thousands2Button.Name = "_thousands2Button";
        _thousands2Button.TabIndex = 43;
        _thousands2Button.Text = "2K";
        _thousands2Button.Click += DenominationButton_Click;
        _thousands1Button.Name = "_thousands1Button";
        _thousands1Button.TabIndex = 49;
        _thousands1Button.Text = "1K";
        _thousands1Button.Click += DenominationButton_Click;
        _hundreds9Button.Name = "_hundreds9Button";
        _hundreds9Button.TabIndex = 2;
        _hundreds9Button.Text = "900";
        _hundreds9Button.Click += DenominationButton_Click;
        _hundreds8Button.Name = "_hundreds8Button";
        _hundreds8Button.TabIndex = 8;
        _hundreds8Button.Text = "800";
        _hundreds8Button.Click += DenominationButton_Click;
        _hundreds7Button.Name = "_hundreds7Button";
        _hundreds7Button.TabIndex = 14;
        _hundreds7Button.Text = "700";
        _hundreds7Button.Click += DenominationButton_Click;
        _hundreds6Button.Name = "_hundreds6Button";
        _hundreds6Button.TabIndex = 20;
        _hundreds6Button.Text = "600";
        _hundreds6Button.Click += DenominationButton_Click;
        _hundreds5Button.Name = "_hundreds5Button";
        _hundreds5Button.TabIndex = 26;
        _hundreds5Button.Text = "500";
        _hundreds5Button.Click += DenominationButton_Click;
        _hundreds4Button.Name = "_hundreds4Button";
        _hundreds4Button.TabIndex = 32;
        _hundreds4Button.Text = "400";
        _hundreds4Button.Click += DenominationButton_Click;
        _hundreds3Button.Name = "_hundreds3Button";
        _hundreds3Button.TabIndex = 38;
        _hundreds3Button.Text = "300";
        _hundreds3Button.Click += DenominationButton_Click;
        _hundreds2Button.Name = "_hundreds2Button";
        _hundreds2Button.TabIndex = 44;
        _hundreds2Button.Text = "200";
        _hundreds2Button.Click += DenominationButton_Click;
        _hundreds1Button.Name = "_hundreds1Button";
        _hundreds1Button.TabIndex = 50;
        _hundreds1Button.Text = "100";
        _hundreds1Button.Click += DenominationButton_Click;
        _tens9Button.Name = "_tens9Button";
        _tens9Button.TabIndex = 3;
        _tens9Button.Text = "$90";
        _tens9Button.Click += DenominationButton_Click;
        _tens8Button.Name = "_tens8Button";
        _tens8Button.TabIndex = 9;
        _tens8Button.Text = "$80";
        _tens8Button.Click += DenominationButton_Click;
        _tens7Button.Name = "_tens7Button";
        _tens7Button.TabIndex = 15;
        _tens7Button.Text = "$70";
        _tens7Button.Click += DenominationButton_Click;
        _tens6Button.Name = "_tens6Button";
        _tens6Button.TabIndex = 21;
        _tens6Button.Text = "$60";
        _tens6Button.Click += DenominationButton_Click;
        _tens5Button.Name = "_tens5Button";
        _tens5Button.TabIndex = 27;
        _tens5Button.Text = "$50";
        _tens5Button.Click += DenominationButton_Click;
        _tens4Button.Name = "_tens4Button";
        _tens4Button.TabIndex = 33;
        _tens4Button.Text = "$40";
        _tens4Button.Click += DenominationButton_Click;
        _tens3Button.Name = "_tens3Button";
        _tens3Button.TabIndex = 39;
        _tens3Button.Text = "$30";
        _tens3Button.Click += DenominationButton_Click;
        _tens2Button.Name = "_tens2Button";
        _tens2Button.TabIndex = 45;
        _tens2Button.Text = "$20";
        _tens2Button.Click += DenominationButton_Click;
        _tens1Button.Name = "_tens1Button";
        _tens1Button.TabIndex = 51;
        _tens1Button.Text = "$10";
        _tens1Button.Click += DenominationButton_Click;
        _ones9Button.Name = "_ones9Button";
        _ones9Button.TabIndex = 4;
        _ones9Button.Text = "$9";
        _ones9Button.Click += DenominationButton_Click;
        _ones8Button.Name = "_ones8Button";
        _ones8Button.TabIndex = 10;
        _ones8Button.Text = "$8";
        _ones8Button.Click += DenominationButton_Click;
        _ones7Button.Name = "_ones7Button";
        _ones7Button.TabIndex = 16;
        _ones7Button.Text = "$7";
        _ones7Button.Click += DenominationButton_Click;
        _ones6Button.Name = "_ones6Button";
        _ones6Button.TabIndex = 22;
        _ones6Button.Text = "$6";
        _ones6Button.Click += DenominationButton_Click;
        _ones5Button.Name = "_ones5Button";
        _ones5Button.TabIndex = 28;
        _ones5Button.Text = "$5";
        _ones5Button.Click += DenominationButton_Click;
        _ones4Button.Name = "_ones4Button";
        _ones4Button.TabIndex = 34;
        _ones4Button.Text = "$4";
        _ones4Button.Click += DenominationButton_Click;
        _ones3Button.Name = "_ones3Button";
        _ones3Button.TabIndex = 40;
        _ones3Button.Text = "$3";
        _ones3Button.Click += DenominationButton_Click;
        _ones2Button.Name = "_ones2Button";
        _ones2Button.TabIndex = 46;
        _ones2Button.Text = "$2";
        _ones2Button.Click += DenominationButton_Click;
        _ones1Button.Name = "_ones1Button";
        _ones1Button.TabIndex = 52;
        _ones1Button.Text = "$1";
        _ones1Button.Click += DenominationButton_Click;
        _tenths9Button.Name = "_tenths9Button";
        _tenths9Button.TabIndex = 5;
        _tenths9Button.Text = ".90";
        _tenths9Button.Click += DenominationButton_Click;
        _tenths8Button.Name = "_tenths8Button";
        _tenths8Button.TabIndex = 11;
        _tenths8Button.Text = ".80";
        _tenths8Button.Click += DenominationButton_Click;
        _tenths7Button.Name = "_tenths7Button";
        _tenths7Button.TabIndex = 17;
        _tenths7Button.Text = ".70";
        _tenths7Button.Click += DenominationButton_Click;
        _tenths6Button.Name = "_tenths6Button";
        _tenths6Button.TabIndex = 23;
        _tenths6Button.Text = ".60";
        _tenths6Button.Click += DenominationButton_Click;
        _tenths5Button.Name = "_tenths5Button";
        _tenths5Button.TabIndex = 29;
        _tenths5Button.Text = ".50";
        _tenths5Button.Click += DenominationButton_Click;
        _tenths4Button.Name = "_tenths4Button";
        _tenths4Button.TabIndex = 35;
        _tenths4Button.Text = ".40";
        _tenths4Button.Click += DenominationButton_Click;
        _tenths3Button.Name = "_tenths3Button";
        _tenths3Button.TabIndex = 41;
        _tenths3Button.Text = ".30";
        _tenths3Button.Click += DenominationButton_Click;
        _tenths2Button.Name = "_tenths2Button";
        _tenths2Button.TabIndex = 47;
        _tenths2Button.Text = ".20";
        _tenths2Button.Click += DenominationButton_Click;
        _tenths1Button.Name = "_tenths1Button";
        _tenths1Button.TabIndex = 53;
        _tenths1Button.Text = ".10";
        _tenths1Button.Click += DenominationButton_Click;
        _hundredths9Button.Name = "_hundredths9Button";
        _hundredths9Button.TabIndex = 6;
        _hundredths9Button.Text = ".09";
        _hundredths9Button.Click += DenominationButton_Click;
        _hundredths8Button.Name = "_hundredths8Button";
        _hundredths8Button.TabIndex = 12;
        _hundredths8Button.Text = ".08";
        _hundredths8Button.Click += DenominationButton_Click;
        _hundredths7Button.Name = "_hundredths7Button";
        _hundredths7Button.TabIndex = 18;
        _hundredths7Button.Text = ".07";
        _hundredths7Button.Click += DenominationButton_Click;
        _hundredths6Button.Name = "_hundredths6Button";
        _hundredths6Button.TabIndex = 24;
        _hundredths6Button.Text = ".06";
        _hundredths6Button.Click += DenominationButton_Click;
        _hundredths5Button.Name = "_hundredths5Button";
        _hundredths5Button.TabIndex = 30;
        _hundredths5Button.Text = ".05";
        _hundredths5Button.Click += DenominationButton_Click;
        _hundredths4Button.Name = "_hundredths4Button";
        _hundredths4Button.TabIndex = 36;
        _hundredths4Button.Text = ".04";
        _hundredths4Button.Click += DenominationButton_Click;
        _hundredths3Button.Name = "_hundredths3Button";
        _hundredths3Button.TabIndex = 42;
        _hundredths3Button.Text = ".03";
        _hundredths3Button.Click += DenominationButton_Click;
        _hundredths2Button.Name = "_hundredths2Button";
        _hundredths2Button.TabIndex = 48;
        _hundredths2Button.Text = ".02";
        _hundredths2Button.Click += DenominationButton_Click;
        _hundredths1Button.Name = "_hundredths1Button";
        _hundredths1Button.TabIndex = 54;
        _hundredths1Button.Text = ".01";
        _hundredths1Button.Click += DenominationButton_Click;
        //
        // _departmentAndActionLayout
        //
        _departmentAndActionLayout.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _departmentAndActionLayout.ColumnCount = 1;
        _departmentAndActionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        _departmentAndActionLayout.Controls.Add(_departmentGrid, 0, 0);
        _departmentAndActionLayout.Controls.Add(_actionGrid, 0, 1);
        _departmentAndActionLayout.Location = new Point(536, 3);
        _departmentAndActionLayout.Name = "_departmentAndActionLayout";
        _departmentAndActionLayout.RowCount = 2;
        _departmentAndActionLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 73F));
        _departmentAndActionLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 27F));
        _departmentAndActionLayout.Size = new Size(325, 660);
        _departmentAndActionLayout.TabIndex = 1;
        //
        // _departmentGrid
        //
        _departmentGrid.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _departmentGrid.ColumnCount = 4;
        _departmentGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        _departmentGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        _departmentGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        _departmentGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        _departmentGrid.Controls.Add(_department01Button, 0, 0);
        _departmentGrid.Controls.Add(_department02Button, 1, 0);
        _departmentGrid.Controls.Add(_department03Button, 2, 0);
        _departmentGrid.Controls.Add(_department04Button, 3, 0);
        _departmentGrid.Controls.Add(_department05Button, 0, 1);
        _departmentGrid.Controls.Add(_department06Button, 1, 1);
        _departmentGrid.Controls.Add(_department07Button, 2, 1);
        _departmentGrid.Controls.Add(_department08Button, 3, 1);
        _departmentGrid.Controls.Add(_department09Button, 0, 2);
        _departmentGrid.Controls.Add(_department10Button, 1, 2);
        _departmentGrid.Controls.Add(_department11Button, 2, 2);
        _departmentGrid.Controls.Add(_department12Button, 3, 2);
        _departmentGrid.Controls.Add(_department13Button, 0, 3);
        _departmentGrid.Controls.Add(_department14Button, 1, 3);
        _departmentGrid.Controls.Add(_department15Button, 2, 3);
        _departmentGrid.Controls.Add(_department16Button, 3, 3);
        _departmentGrid.Controls.Add(_department17Button, 0, 4);
        _departmentGrid.Controls.Add(_department18Button, 1, 4);
        _departmentGrid.Controls.Add(_department19Button, 2, 4);
        _departmentGrid.Controls.Add(_department20Button, 3, 4);
        _departmentGrid.Location = new Point(3, 3);
        _departmentGrid.Name = "_departmentGrid";
        _departmentGrid.RowCount = 5;
        _departmentGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        _departmentGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        _departmentGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        _departmentGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        _departmentGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        _departmentGrid.Size = new Size(319, 475);
        _departmentGrid.TabIndex = 0;
        _department01Button.Name = "_department01Button";
        _department01Button.TabIndex = 55;
        _department01Button.Text = "DEP 01";
        _department01Button.Click += DepartmentButton_Click;
        _department02Button.Name = "_department02Button";
        _department02Button.TabIndex = 56;
        _department02Button.Text = "DEP 02";
        _department02Button.Click += DepartmentButton_Click;
        _department03Button.Name = "_department03Button";
        _department03Button.TabIndex = 57;
        _department03Button.Text = "DEP 03";
        _department03Button.Click += DepartmentButton_Click;
        _department04Button.Name = "_department04Button";
        _department04Button.TabIndex = 58;
        _department04Button.Text = "DEP 04";
        _department04Button.Click += DepartmentButton_Click;
        _department05Button.Name = "_department05Button";
        _department05Button.TabIndex = 59;
        _department05Button.Text = "DEP 05";
        _department05Button.Click += DepartmentButton_Click;
        _department06Button.Name = "_department06Button";
        _department06Button.TabIndex = 60;
        _department06Button.Text = "DEP 06";
        _department06Button.Click += DepartmentButton_Click;
        _department07Button.Name = "_department07Button";
        _department07Button.TabIndex = 61;
        _department07Button.Text = "DEP 07";
        _department07Button.Click += DepartmentButton_Click;
        _department08Button.Name = "_department08Button";
        _department08Button.TabIndex = 62;
        _department08Button.Text = "DEP 08";
        _department08Button.Click += DepartmentButton_Click;
        _department09Button.Name = "_department09Button";
        _department09Button.TabIndex = 63;
        _department09Button.Text = "DEP 09";
        _department09Button.Click += DepartmentButton_Click;
        _department10Button.Name = "_department10Button";
        _department10Button.TabIndex = 64;
        _department10Button.Text = "DEP 10";
        _department10Button.Click += DepartmentButton_Click;
        _department11Button.Name = "_department11Button";
        _department11Button.TabIndex = 65;
        _department11Button.Text = "DEP 11";
        _department11Button.Click += DepartmentButton_Click;
        _department12Button.Name = "_department12Button";
        _department12Button.TabIndex = 66;
        _department12Button.Text = "DEP 12";
        _department12Button.Click += DepartmentButton_Click;
        _department13Button.Name = "_department13Button";
        _department13Button.TabIndex = 67;
        _department13Button.Text = "DEP 13";
        _department13Button.Click += DepartmentButton_Click;
        _department14Button.Name = "_department14Button";
        _department14Button.TabIndex = 68;
        _department14Button.Text = "DEP 14";
        _department14Button.Click += DepartmentButton_Click;
        _department15Button.Name = "_department15Button";
        _department15Button.TabIndex = 69;
        _department15Button.Text = "DEP 15";
        _department15Button.Click += DepartmentButton_Click;
        _department16Button.Name = "_department16Button";
        _department16Button.TabIndex = 70;
        _department16Button.Text = "DEP 16";
        _department16Button.Click += DepartmentButton_Click;
        _department17Button.Name = "_department17Button";
        _department17Button.TabIndex = 71;
        _department17Button.Text = "DEP 17";
        _department17Button.Click += DepartmentButton_Click;
        _department18Button.Name = "_department18Button";
        _department18Button.TabIndex = 72;
        _department18Button.Text = "DEP 18";
        _department18Button.Click += DepartmentButton_Click;
        _department19Button.Name = "_department19Button";
        _department19Button.TabIndex = 73;
        _department19Button.Text = "DEP 19";
        _department19Button.Click += DepartmentButton_Click;
        _department20Button.Name = "_department20Button";
        _department20Button.TabIndex = 74;
        _department20Button.Text = "DEP 20";
        _department20Button.Click += DepartmentButton_Click;
        //
        // _actionGrid
        //
        _actionGrid.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _actionGrid.ColumnCount = 2;
        _actionGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        _actionGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        _actionGrid.Controls.Add(_taxButton, 0, 0);
        _actionGrid.Controls.Add(_voidButton, 1, 0);
        _actionGrid.Controls.Add(_subtotalButton, 0, 1);
        _actionGrid.Controls.Add(_totalButton, 1, 1);
        _actionGrid.Location = new Point(3, 484);
        _actionGrid.Name = "_actionGrid";
        _actionGrid.RowCount = 2;
        _actionGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        _actionGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        _actionGrid.Size = new Size(319, 173);
        _actionGrid.TabIndex = 1;
        _taxButton.Name = "_taxButton";
        _taxButton.TabIndex = 75;
        _taxButton.Text = "TAX 8.25%";
        _voidButton.Name = "_voidButton";
        _voidButton.TabIndex = 76;
        _voidButton.Text = "VOID";
        _subtotalButton.Name = "_subtotalButton";
        _subtotalButton.TabIndex = 77;
        _subtotalButton.Text = "SUBTOTAL";
        _totalButton.Name = "_totalButton";
        _totalButton.TabIndex = 78;
        _totalButton.Text = "TOTAL";
        _taxButton.Click += TaxButton_Click;
        _voidButton.Click += VoidButton_Click;
        _subtotalButton.Click += SubtotalButton_Click;
        _totalButton.Click += TotalButton_Click;
        //
        // _receiptGroupBox
        //
        _receiptGroupBox.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _receiptGroupBox.Controls.Add(_receiptTextBox);
        _receiptGroupBox.Location = new Point(887, 11);
        _receiptGroupBox.Name = "_receiptGroupBox";
        _receiptGroupBox.Padding = new Padding(10);
        _receiptGroupBox.Size = new Size(302, 798);
        _receiptGroupBox.TabIndex = 1;
        _receiptGroupBox.TabStop = false;
        _receiptGroupBox.Text = "Receipt printer";
        //
        // _receiptTextBox
        //
        _receiptTextBox.AccessibleName = "Printed receipt";
        _receiptTextBox.BackColor = Color.FromArgb(255, 253, 240);
        _receiptTextBox.BorderStyle = BorderStyle.None;
        _receiptTextBox.DetectUrls = false;
        _receiptTextBox.Dock = DockStyle.Fill;
        _receiptTextBox.Font = new Font("Consolas", 10F, FontStyle.Regular, GraphicsUnit.Point, 0);
        _receiptTextBox.ForeColor = Color.FromArgb(28, 28, 24);
        _receiptTextBox.Location = new Point(10, 34);
        _receiptTextBox.Name = "_receiptTextBox";
        _receiptTextBox.ReadOnly = true;
        _receiptTextBox.ScrollBars = RichTextBoxScrollBars.Both;
        _receiptTextBox.Size = new Size(282, 754);
        _receiptTextBox.TabIndex = 0;
        _receiptTextBox.Text = "";
        _receiptTextBox.WordWrap = false;
        //
        // CashRegisterView
        //
        AutoScaleMode = AutoScaleMode.Inherit;
        AutoScroll = true;
        AutoScrollMinSize = new Size(1200, 820);
        Controls.Add(_rootLayout);
        Name = "CashRegisterView";
        Size = new Size(1200, 820);
        _rootLayout.ResumeLayout(false);
        _registerLayout.ResumeLayout(false);
        _keyBodyLayout.ResumeLayout(false);
        _denominationGrid.ResumeLayout(false);
        _denominationGrid.PerformLayout();
        _departmentAndActionLayout.ResumeLayout(false);
        _departmentGrid.ResumeLayout(false);
        _actionGrid.ResumeLayout(false);
        _receiptGroupBox.ResumeLayout(false);
        ResumeLayout(false);
    }

    #endregion

    private TableLayoutPanel _rootLayout;
    private TableLayoutPanel _registerLayout;
    private SevenSegmentDisplay _display;
    private TableLayoutPanel _keyBodyLayout;
    private TableLayoutPanel _denominationGrid;
    private Label _thousandsHeaderLabel;
    private Label _hundredsHeaderLabel;
    private Label _tensHeaderLabel;
    private Label _onesHeaderLabel;
    private Label _tenthsHeaderLabel;
    private Label _hundredthsHeaderLabel;
    private Button _thousands9Button;
    private Button _thousands8Button;
    private Button _thousands7Button;
    private Button _thousands6Button;
    private Button _thousands5Button;
    private Button _thousands4Button;
    private Button _thousands3Button;
    private Button _thousands2Button;
    private Button _thousands1Button;
    private Button _hundreds9Button;
    private Button _hundreds8Button;
    private Button _hundreds7Button;
    private Button _hundreds6Button;
    private Button _hundreds5Button;
    private Button _hundreds4Button;
    private Button _hundreds3Button;
    private Button _hundreds2Button;
    private Button _hundreds1Button;
    private Button _tens9Button;
    private Button _tens8Button;
    private Button _tens7Button;
    private Button _tens6Button;
    private Button _tens5Button;
    private Button _tens4Button;
    private Button _tens3Button;
    private Button _tens2Button;
    private Button _tens1Button;
    private Button _ones9Button;
    private Button _ones8Button;
    private Button _ones7Button;
    private Button _ones6Button;
    private Button _ones5Button;
    private Button _ones4Button;
    private Button _ones3Button;
    private Button _ones2Button;
    private Button _ones1Button;
    private Button _tenths9Button;
    private Button _tenths8Button;
    private Button _tenths7Button;
    private Button _tenths6Button;
    private Button _tenths5Button;
    private Button _tenths4Button;
    private Button _tenths3Button;
    private Button _tenths2Button;
    private Button _tenths1Button;
    private Button _hundredths9Button;
    private Button _hundredths8Button;
    private Button _hundredths7Button;
    private Button _hundredths6Button;
    private Button _hundredths5Button;
    private Button _hundredths4Button;
    private Button _hundredths3Button;
    private Button _hundredths2Button;
    private Button _hundredths1Button;
    private TableLayoutPanel _departmentAndActionLayout;
    private TableLayoutPanel _departmentGrid;
    private Button _department01Button;
    private Button _department02Button;
    private Button _department03Button;
    private Button _department04Button;
    private Button _department05Button;
    private Button _department06Button;
    private Button _department07Button;
    private Button _department08Button;
    private Button _department09Button;
    private Button _department10Button;
    private Button _department11Button;
    private Button _department12Button;
    private Button _department13Button;
    private Button _department14Button;
    private Button _department15Button;
    private Button _department16Button;
    private Button _department17Button;
    private Button _department18Button;
    private Button _department19Button;
    private Button _department20Button;
    private TableLayoutPanel _actionGrid;
    private Button _taxButton;
    private Button _voidButton;
    private Button _subtotalButton;
    private Button _totalButton;
    private GroupBox _receiptGroupBox;
    private RichTextBox _receiptTextBox;
}
