<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LayoutTests.App</RootNamespace>
    <AssemblyName>LayoutTests.App</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\WARP\src\WarpToolkit.WinForms.AppServices\WarpToolkit.WinForms.AppServices.csproj" />
    <ProjectReference Include="..\..\..\..\..\WARP\src\WarpToolkit.WinForms.Extensions\WarpToolkit.WinForms.Extensions.csproj" />
    <ProjectReference Include="..\..\..\..\..\WARP\src\WarpToolkit.WinForms\WarpToolkit.WinForms.csproj" />
  </ItemGroup>

</Project>
