namespace LargeFormSmokeTest.Sections
{
    partial class MantelbogenSection
    {
        /// <summary>Required designer variable.</summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>Clean up any resources being used.</summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            _groupBox = new System.Windows.Forms.GroupBox();
            _table = new System.Windows.Forms.TableLayoutPanel();
            _ban0 = new LargeFormSmokeTest.Controls.SectionLabel();
            _lbl1 = new System.Windows.Forms.Label();
            _inp1 = new System.Windows.Forms.TextBox();
            _lbl2 = new System.Windows.Forms.Label();
            _inp2 = new System.Windows.Forms.TextBox();
            _lbl3 = new System.Windows.Forms.Label();
            _inp3 = new System.Windows.Forms.NumericUpDown();
            _lbl4 = new System.Windows.Forms.Label();
            _inp4 = new System.Windows.Forms.TextBox();
            _lbl5 = new System.Windows.Forms.Label();
            _rad5 = new System.Windows.Forms.FlowLayoutPanel();
            _rad5_0 = new System.Windows.Forms.RadioButton();
            _rad5_1 = new System.Windows.Forms.RadioButton();
            _rad5_2 = new System.Windows.Forms.RadioButton();
            _rad5_3 = new System.Windows.Forms.RadioButton();
            _lbl6 = new System.Windows.Forms.Label();
            _rad6 = new System.Windows.Forms.FlowLayoutPanel();
            _rad6_0 = new System.Windows.Forms.RadioButton();
            _rad6_1 = new System.Windows.Forms.RadioButton();
            _rad6_2 = new System.Windows.Forms.RadioButton();
            _rad6_3 = new System.Windows.Forms.RadioButton();
            _lbl7 = new System.Windows.Forms.Label();
            _inp7 = new System.Windows.Forms.TextBox();
            _inp8 = new System.Windows.Forms.CheckBox();
            _sep9 = new LargeFormSmokeTest.Controls.SeparatorLine();
            _ban10 = new LargeFormSmokeTest.Controls.SectionLabel();
            _lbl11 = new System.Windows.Forms.Label();
            _inp11 = new System.Windows.Forms.NumericUpDown();
            _lbl12 = new System.Windows.Forms.Label();
            _inp12 = new System.Windows.Forms.NumericUpDown();
            _lbl13 = new System.Windows.Forms.Label();
            _inp13 = new System.Windows.Forms.NumericUpDown();
            _lbl14 = new System.Windows.Forms.Label();
            _rad14 = new System.Windows.Forms.FlowLayoutPanel();
            _rad14_0 = new System.Windows.Forms.RadioButton();
            _rad14_1 = new System.Windows.Forms.RadioButton();
            _rad14_2 = new System.Windows.Forms.RadioButton();
            _lbl15 = new System.Windows.Forms.Label();
            _rad15 = new System.Windows.Forms.FlowLayoutPanel();
            _rad15_0 = new System.Windows.Forms.RadioButton();
            _rad15_1 = new System.Windows.Forms.RadioButton();
            _table.SuspendLayout();
            _groupBox.SuspendLayout();
            _rad5.SuspendLayout();
            _rad6.SuspendLayout();
            _rad14.SuspendLayout();
            _rad15.SuspendLayout();
            SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)_inp3).BeginInit();
            ((System.ComponentModel.ISupportInitialize)_inp11).BeginInit();
            ((System.ComponentModel.ISupportInitialize)_inp12).BeginInit();
            ((System.ComponentModel.ISupportInitialize)_inp13).BeginInit();
            _table.ColumnCount = 2;
            _table.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 240F));
            _table.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            _table.RowCount = 16;
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            _table.Dock = System.Windows.Forms.DockStyle.Top;
            _table.AutoSize = true;
            _table.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            _table.Padding = new System.Windows.Forms.Padding(4);
            _table.Name = "_table";
            _ban0.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _ban0.Margin = new System.Windows.Forms.Padding(0, 6, 0, 4);
            _ban0.Name = "_ban0";
            _ban0.Text = "Stammdaten";
            _table.Controls.Add(_ban0, 0, 0);
            _table.SetColumnSpan(_ban0, 2);
            _lbl1.Anchor = System.Windows.Forms.AnchorStyles.Left;
            _lbl1.AutoSize = true;
            _lbl1.Margin = new System.Windows.Forms.Padding(3, 0, 8, 0);
            _lbl1.Name = "_lbl1";
            _lbl1.Text = "Steuernummer";
            _table.Controls.Add(_lbl1, 0, 1);
            _inp1.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _inp1.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            _inp1.Name = "_inp1";
            _table.Controls.Add(_inp1, 1, 1);
            _lbl2.Anchor = System.Windows.Forms.AnchorStyles.Left;
            _lbl2.AutoSize = true;
            _lbl2.Margin = new System.Windows.Forms.Padding(3, 0, 8, 0);
            _lbl2.Name = "_lbl2";
            _lbl2.Text = "Finanzamt";
            _table.Controls.Add(_lbl2, 0, 2);
            _inp2.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _inp2.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            _inp2.Name = "_inp2";
            _table.Controls.Add(_inp2, 1, 2);
            _lbl3.Anchor = System.Windows.Forms.AnchorStyles.Left;
            _lbl3.AutoSize = true;
            _lbl3.Margin = new System.Windows.Forms.Padding(3, 0, 8, 0);
            _lbl3.Name = "_lbl3";
            _lbl3.Text = "Veranlagungsjahr";
            _table.Controls.Add(_lbl3, 0, 3);
            _inp3.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _inp3.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            _inp3.Name = "_inp3";
            _inp3.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            _table.Controls.Add(_inp3, 1, 3);
            _lbl4.Anchor = System.Windows.Forms.AnchorStyles.Left;
            _lbl4.AutoSize = true;
            _lbl4.Margin = new System.Windows.Forms.Padding(3, 0, 8, 0);
            _lbl4.Name = "_lbl4";
            _lbl4.Text = "Identifikationsnummer";
            _table.Controls.Add(_lbl4, 0, 4);
            _inp4.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _inp4.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            _inp4.Name = "_inp4";
            _table.Controls.Add(_inp4, 1, 4);
            _lbl5.Anchor = System.Windows.Forms.AnchorStyles.Left;
            _lbl5.AutoSize = true;
            _lbl5.Margin = new System.Windows.Forms.Padding(3, 0, 8, 0);
            _lbl5.Name = "_lbl5";
            _lbl5.Text = "Familienstand";
            _table.Controls.Add(_lbl5, 0, 5);
            _rad5.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _rad5.AutoSize = true;
            _rad5.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            _rad5.FlowDirection = System.Windows.Forms.FlowDirection.LeftToRight;
            _rad5.WrapContents = true;
            _rad5.Margin = new System.Windows.Forms.Padding(3, 1, 3, 1);
            _rad5.Name = "_rad5";
            _rad5_0.AutoSize = true;
            _rad5_0.Margin = new System.Windows.Forms.Padding(3, 3, 14, 3);
            _rad5_0.Name = "_rad5_0";
            _rad5_0.Text = "ledig";
            _rad5.Controls.Add(_rad5_0);
            _rad5_1.AutoSize = true;
            _rad5_1.Margin = new System.Windows.Forms.Padding(3, 3, 14, 3);
            _rad5_1.Name = "_rad5_1";
            _rad5_1.Text = "verheiratet";
            _rad5.Controls.Add(_rad5_1);
            _rad5_2.AutoSize = true;
            _rad5_2.Margin = new System.Windows.Forms.Padding(3, 3, 14, 3);
            _rad5_2.Name = "_rad5_2";
            _rad5_2.Text = "geschieden";
            _rad5.Controls.Add(_rad5_2);
            _rad5_3.AutoSize = true;
            _rad5_3.Margin = new System.Windows.Forms.Padding(3, 3, 14, 3);
            _rad5_3.Name = "_rad5_3";
            _rad5_3.Text = "verwitwet";
            _rad5.Controls.Add(_rad5_3);
            _table.Controls.Add(_rad5, 1, 5);
            _lbl6.Anchor = System.Windows.Forms.AnchorStyles.Left;
            _lbl6.AutoSize = true;
            _lbl6.Margin = new System.Windows.Forms.Padding(3, 0, 8, 0);
            _lbl6.Name = "_lbl6";
            _lbl6.Text = "Religionszugehörigkeit";
            _table.Controls.Add(_lbl6, 0, 6);
            _rad6.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _rad6.AutoSize = true;
            _rad6.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            _rad6.FlowDirection = System.Windows.Forms.FlowDirection.LeftToRight;
            _rad6.WrapContents = true;
            _rad6.Margin = new System.Windows.Forms.Padding(3, 1, 3, 1);
            _rad6.Name = "_rad6";
            _rad6_0.AutoSize = true;
            _rad6_0.Margin = new System.Windows.Forms.Padding(3, 3, 14, 3);
            _rad6_0.Name = "_rad6_0";
            _rad6_0.Text = "keine";
            _rad6.Controls.Add(_rad6_0);
            _rad6_1.AutoSize = true;
            _rad6_1.Margin = new System.Windows.Forms.Padding(3, 3, 14, 3);
            _rad6_1.Name = "_rad6_1";
            _rad6_1.Text = "rk";
            _rad6.Controls.Add(_rad6_1);
            _rad6_2.AutoSize = true;
            _rad6_2.Margin = new System.Windows.Forms.Padding(3, 3, 14, 3);
            _rad6_2.Name = "_rad6_2";
            _rad6_2.Text = "ev";
            _rad6.Controls.Add(_rad6_2);
            _rad6_3.AutoSize = true;
            _rad6_3.Margin = new System.Windows.Forms.Padding(3, 3, 14, 3);
            _rad6_3.Name = "_rad6_3";
            _rad6_3.Text = "sonstige";
            _rad6.Controls.Add(_rad6_3);
            _table.Controls.Add(_rad6, 1, 6);
            _lbl7.Anchor = System.Windows.Forms.AnchorStyles.Left;
            _lbl7.AutoSize = true;
            _lbl7.Margin = new System.Windows.Forms.Padding(3, 0, 8, 0);
            _lbl7.Name = "_lbl7";
            _lbl7.Text = "IBAN";
            _table.Controls.Add(_lbl7, 0, 7);
            _inp7.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _inp7.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            _inp7.Name = "_inp7";
            _table.Controls.Add(_inp7, 1, 7);
            _inp8.Anchor = System.Windows.Forms.AnchorStyles.Left;
            _inp8.AutoSize = true;
            _inp8.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            _inp8.Name = "_inp8";
            _inp8.Text = "Elektronisch übermittelt (ELSTER)";
            _table.Controls.Add(_inp8, 0, 8);
            _table.SetColumnSpan(_inp8, 2);
            _sep9.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _sep9.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            _sep9.Name = "_sep9";
            _table.Controls.Add(_sep9, 0, 9);
            _table.SetColumnSpan(_sep9, 2);
            _ban10.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _ban10.Margin = new System.Windows.Forms.Padding(0, 6, 0, 4);
            _ban10.Name = "_ban10";
            _ban10.Text = "Festsetzung";
            _table.Controls.Add(_ban10, 0, 10);
            _table.SetColumnSpan(_ban10, 2);
            _lbl11.Anchor = System.Windows.Forms.AnchorStyles.Left;
            _lbl11.AutoSize = true;
            _lbl11.Margin = new System.Windows.Forms.Padding(3, 0, 8, 0);
            _lbl11.Name = "_lbl11";
            _lbl11.Text = "Bemessungsgrundlage";
            _table.Controls.Add(_lbl11, 0, 11);
            _inp11.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _inp11.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            _inp11.Name = "_inp11";
            _inp11.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            _inp11.DecimalPlaces = 2;
            _inp11.ThousandsSeparator = true;
            _table.Controls.Add(_inp11, 1, 11);
            _lbl12.Anchor = System.Windows.Forms.AnchorStyles.Left;
            _lbl12.AutoSize = true;
            _lbl12.Margin = new System.Windows.Forms.Padding(3, 0, 8, 0);
            _lbl12.Name = "_lbl12";
            _lbl12.Text = "Festgesetzte Steuer";
            _table.Controls.Add(_lbl12, 0, 12);
            _inp12.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _inp12.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            _inp12.Name = "_inp12";
            _inp12.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            _inp12.DecimalPlaces = 2;
            _inp12.ThousandsSeparator = true;
            _table.Controls.Add(_inp12, 1, 12);
            _lbl13.Anchor = System.Windows.Forms.AnchorStyles.Left;
            _lbl13.AutoSize = true;
            _lbl13.Margin = new System.Windows.Forms.Padding(3, 0, 8, 0);
            _lbl13.Name = "_lbl13";
            _lbl13.Text = "Ausstehender Betrag";
            _table.Controls.Add(_lbl13, 0, 13);
            _inp13.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _inp13.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            _inp13.Name = "_inp13";
            _inp13.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            _inp13.DecimalPlaces = 2;
            _inp13.ThousandsSeparator = true;
            _table.Controls.Add(_inp13, 1, 13);
            _lbl14.Anchor = System.Windows.Forms.AnchorStyles.Left;
            _lbl14.AutoSize = true;
            _lbl14.Margin = new System.Windows.Forms.Padding(3, 0, 8, 0);
            _lbl14.Name = "_lbl14";
            _lbl14.Text = "Status";
            _table.Controls.Add(_lbl14, 0, 14);
            _rad14.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _rad14.AutoSize = true;
            _rad14.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            _rad14.FlowDirection = System.Windows.Forms.FlowDirection.LeftToRight;
            _rad14.WrapContents = true;
            _rad14.Margin = new System.Windows.Forms.Padding(3, 1, 3, 1);
            _rad14.Name = "_rad14";
            _rad14_0.AutoSize = true;
            _rad14_0.Margin = new System.Windows.Forms.Padding(3, 3, 14, 3);
            _rad14_0.Name = "_rad14_0";
            _rad14_0.Text = "offen";
            _rad14.Controls.Add(_rad14_0);
            _rad14_1.AutoSize = true;
            _rad14_1.Margin = new System.Windows.Forms.Padding(3, 3, 14, 3);
            _rad14_1.Name = "_rad14_1";
            _rad14_1.Text = "beglichen";
            _rad14.Controls.Add(_rad14_1);
            _rad14_2.AutoSize = true;
            _rad14_2.Margin = new System.Windows.Forms.Padding(3, 3, 14, 3);
            _rad14_2.Name = "_rad14_2";
            _rad14_2.Text = "gestundet";
            _rad14.Controls.Add(_rad14_2);
            _table.Controls.Add(_rad14, 1, 14);
            _lbl15.Anchor = System.Windows.Forms.AnchorStyles.Left;
            _lbl15.AutoSize = true;
            _lbl15.Margin = new System.Windows.Forms.Padding(3, 0, 8, 0);
            _lbl15.Name = "_lbl15";
            _lbl15.Text = "Abgabepflicht";
            _table.Controls.Add(_lbl15, 0, 15);
            _rad15.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            _rad15.AutoSize = true;
            _rad15.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            _rad15.FlowDirection = System.Windows.Forms.FlowDirection.LeftToRight;
            _rad15.WrapContents = true;
            _rad15.Margin = new System.Windows.Forms.Padding(3, 1, 3, 1);
            _rad15.Name = "_rad15";
            _rad15_0.AutoSize = true;
            _rad15_0.Margin = new System.Windows.Forms.Padding(3, 3, 14, 3);
            _rad15_0.Name = "_rad15_0";
            _rad15_0.Text = "Einkommensteuer";
            _rad15.Controls.Add(_rad15_0);
            _rad15_1.AutoSize = true;
            _rad15_1.Margin = new System.Windows.Forms.Padding(3, 3, 14, 3);
            _rad15_1.Name = "_rad15_1";
            _rad15_1.Text = "Lohn- & Einkommensteuer";
            _rad15.Controls.Add(_rad15_1);
            _table.Controls.Add(_rad15, 1, 15);
            _groupBox.Controls.Add(_table);
            _groupBox.Dock = System.Windows.Forms.DockStyle.Top;
            _groupBox.AutoSize = true;
            _groupBox.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            _groupBox.Padding = new System.Windows.Forms.Padding(10, 6, 10, 12);
            _groupBox.Name = "_groupBox";
            _groupBox.Text = "";
            AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            AutoSize = true;
            AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            Controls.Add(_groupBox);
            Margin = new System.Windows.Forms.Padding(0);
            Name = "MantelbogenSection";
            Size = new System.Drawing.Size(720, 320);
            ((System.ComponentModel.ISupportInitialize)_inp3).EndInit();
            ((System.ComponentModel.ISupportInitialize)_inp11).EndInit();
            ((System.ComponentModel.ISupportInitialize)_inp12).EndInit();
            ((System.ComponentModel.ISupportInitialize)_inp13).EndInit();
            _rad5.ResumeLayout(false);
            _rad5.PerformLayout();
            _rad6.ResumeLayout(false);
            _rad6.PerformLayout();
            _rad14.ResumeLayout(false);
            _rad14.PerformLayout();
            _rad15.ResumeLayout(false);
            _rad15.PerformLayout();
            _table.ResumeLayout(false);
            _table.PerformLayout();
            _groupBox.ResumeLayout(false);
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.GroupBox _groupBox;
        private System.Windows.Forms.TableLayoutPanel _table;
        private LargeFormSmokeTest.Controls.SectionLabel _ban0;
        private System.Windows.Forms.Label _lbl1;
        private System.Windows.Forms.TextBox _inp1;
        private System.Windows.Forms.Label _lbl2;
        private System.Windows.Forms.TextBox _inp2;
        private System.Windows.Forms.Label _lbl3;
        private System.Windows.Forms.NumericUpDown _inp3;
        private System.Windows.Forms.Label _lbl4;
        private System.Windows.Forms.TextBox _inp4;
        private System.Windows.Forms.Label _lbl5;
        private System.Windows.Forms.FlowLayoutPanel _rad5;
        private System.Windows.Forms.RadioButton _rad5_0;
        private System.Windows.Forms.RadioButton _rad5_1;
        private System.Windows.Forms.RadioButton _rad5_2;
        private System.Windows.Forms.RadioButton _rad5_3;
        private System.Windows.Forms.Label _lbl6;
        private System.Windows.Forms.FlowLayoutPanel _rad6;
        private System.Windows.Forms.RadioButton _rad6_0;
        private System.Windows.Forms.RadioButton _rad6_1;
        private System.Windows.Forms.RadioButton _rad6_2;
        private System.Windows.Forms.RadioButton _rad6_3;
        private System.Windows.Forms.Label _lbl7;
        private System.Windows.Forms.TextBox _inp7;
        private System.Windows.Forms.CheckBox _inp8;
        private LargeFormSmokeTest.Controls.SeparatorLine _sep9;
        private LargeFormSmokeTest.Controls.SectionLabel _ban10;
        private System.Windows.Forms.Label _lbl11;
        private System.Windows.Forms.NumericUpDown _inp11;
        private System.Windows.Forms.Label _lbl12;
        private System.Windows.Forms.NumericUpDown _inp12;
        private System.Windows.Forms.Label _lbl13;
        private System.Windows.Forms.NumericUpDown _inp13;
        private System.Windows.Forms.Label _lbl14;
        private System.Windows.Forms.FlowLayoutPanel _rad14;
        private System.Windows.Forms.RadioButton _rad14_0;
        private System.Windows.Forms.RadioButton _rad14_1;
        private System.Windows.Forms.RadioButton _rad14_2;
        private System.Windows.Forms.Label _lbl15;
        private System.Windows.Forms.FlowLayoutPanel _rad15;
        private System.Windows.Forms.RadioButton _rad15_0;
        private System.Windows.Forms.RadioButton _rad15_1;
    }
}
