using Microsoft.Win32;
using WinBaas.Models;

namespace WinBaas.Services;

/// <inheritdoc cref="IRegistryCatalog"/>
public sealed class RegistryCatalog : IRegistryCatalog
{
    private readonly IReadOnlyList<RegistryDescriptor> _entries =
    [
        Dword("Show hidden OS files", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "ShowSuperHidden",
            "Explorer toggle for protected operating-system files.",
            "Explorer: show protected operating-system files. Frequently changed during diagnostics or advanced troubleshooting."),
        Dword("Show hidden files", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "Hidden",
            "Explorer toggle for hidden files and folders.",
            "Explorer: show hidden files and folders in File Explorer."),
        Dword("Show file extensions", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "HideFileExt",
            "Whether File Explorer hides known file-name extensions.",
            "Explorer: hide known file-name extensions. Power users often flip this off so extensions stay visible."),
        Dword("Explorer launch target", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "LaunchTo",
            "Whether File Explorer opens to Home/Quick Access or This PC.",
            "Explorer: launch target for new File Explorer windows (for example Home/Quick Access versus This PC)."),
        Dword("Item check boxes", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "AutoCheckSelect",
            "Show check boxes for item selection.",
            "Explorer: use item-selection check boxes in File Explorer."),
        Dword("Taskbar alignment", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "TaskbarAl",
            "Windows 11 taskbar alignment setting.",
            "Taskbar: alignment of Start and pinned apps (center versus left)."),
        Dword("Widgets button", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "TaskbarDa",
            "Taskbar Widgets button visibility.",
            "Taskbar: show or hide the Widgets button."),
        Dword("Chat / Teams button", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "TaskbarMn",
            "Taskbar Chat button visibility.",
            "Taskbar: show or hide the Chat / Microsoft Teams button."),
        Dword("Task View button", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "ShowTaskViewButton",
            "Taskbar Task View button visibility.",
            "Taskbar: show or hide the Task View button."),
        Dword("Search box mode", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Search", "SearchboxTaskbarMode",
            "Taskbar search UI mode.",
            "Search: taskbar search-box mode (hidden, icon, label, or full search box)."),
        Dword("Bing web search", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Search", "BingSearchEnabled",
            "Include Bing/web results in Start or taskbar search.",
            "Search: allow Bing/web results in the Windows search experience."),
        Dword("Cortana consent", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Search", "CortanaConsent",
            "Legacy Cortana / cloud-search consent state.",
            "Search: legacy Cortana consent / cloud-backed search setting."),
        Dword("Telemetry level", RegistryHive.LocalMachine, @"SOFTWARE\Policies\Microsoft\Windows\DataCollection", "AllowTelemetry",
            "Windows telemetry policy value.",
            "Privacy / telemetry: policy-controlled telemetry level. HKLM policy value; read-only on non-elevated runs is expected.",
            requiresElevation: true),
        Dword("Tailored experiences", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Privacy", "TailoredExperiencesWithDiagnosticDataEnabled",
            "Use diagnostic data for tailored experiences.",
            "Privacy: tailored experiences based on diagnostic data."),
        Dword("Track Start suggestions", RegistryHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "Start_TrackProgs",
            "Track recently used apps for Start recommendations.",
            "Privacy / UX: track frequently used apps so Start and Search can surface them."),
        String("Pause updates until", RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\WindowsUpdate\UX\Settings", "PauseUpdatesExpiryTime",
            "Windows Update pause-until timestamp.",
            "Windows Update: pause-updates expiry timestamp. HKLM value; reading may require elevation.", requiresElevation: true),
        Dword("Branch readiness", RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\WindowsUpdate\UX\Settings", "BranchReadinessLevel",
            "Windows Update servicing branch setting.",
            "Windows Update: branch readiness / servicing channel level. HKLM value; reading may require elevation.", requiresElevation: true),
        Dword("Developer mode", RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock", "AllowDevelopmentWithoutDevLicense",
            "Enable sideloading / developer mode without a dev license.",
            "Developer mode: allow development without a developer license. HKLM value; reading or restoring usually requires elevation.", requiresElevation: true),
        Dword("Allow trusted apps", RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock", "AllowAllTrustedApps",
            "Allow sideloading trusted apps.",
            "Developer mode: allow all trusted apps to be sideloaded. HKLM value; reading or restoring usually requires elevation.", requiresElevation: true),
        Dword("Long paths enabled", RegistryHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\FileSystem", "LongPathsEnabled",
            "Enable Win32 long-path support.",
            "Developer mode / filesystem: enable long-path support for Win32 APIs. HKLM value; reading or restoring usually requires elevation.", requiresElevation: true),
        String("Classic context menu", RegistryHive.CurrentUser, @"Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32", string.Empty,
            "Restore the classic Windows 11 context menu.",
            "Windows 11 shell tweak: restore the classic context menu by setting the default value of the shell extension override key.",
            defaultValue: string.Empty),
        Dword("Hibernate enabled", RegistryHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Power", "HibernateEnabled",
            "Hibernate availability.",
            "Power / UX: whether hibernation is enabled on the machine. HKLM value; reading or restoring usually requires elevation.", requiresElevation: true),
        Dword("Verbose boot/status", RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "VerboseStatus",
            "Show verbose startup and shutdown status messages.",
            "Power / UX: show verbose startup, logon, logoff, shutdown and restart status messages. HKLM value; reading or restoring usually requires elevation.", requiresElevation: true),
        Dword("DisableAntiSpyware", RegistryHive.LocalMachine, @"SOFTWARE\Policies\Microsoft\Windows Defender", "DisableAntiSpyware",
            "Legacy Defender policy value.",
            "Defender: legacy policy-only value kept for information when present. Modern Windows versions may ignore it. HKLM policy value; reading may require elevation.",
            informationalOnly: true,
            requiresElevation: true),

        // --- Power / thermal throttling ---------------------------------------
        Dword("Power throttling off", RegistryHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Power\PowerThrottling", "PowerThrottlingOff",
            "Disable CPU power throttling for background work.",
            "Power: when set to 1, disables Windows power throttling so background threads are not parked for efficiency. HKLM value; restoring requires elevation.",
            requiresElevation: true),
        Dword("Fast startup", RegistryHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Session Manager\Power", "HiberbootEnabled",
            "Hybrid (fast) startup toggle.",
            "Power: hybrid boot / fast startup. Often disabled by developers to get a true cold boot. HKLM value; restoring requires elevation.",
            requiresElevation: true),
        Dword("Modern standby override", RegistryHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Power", "PlatformAoAcOverride",
            "Disable Modern Standby (S0 low-power idle).",
            "Power / thermal: PlatformAoAcOverride forces classic S3 sleep instead of Modern Standby on supported hardware. HKLM value; restoring requires elevation.",
            requiresElevation: true),

        // --- OneDrive workload throttling -------------------------------------
        Dword("OneDrive upload limit", RegistryHive.LocalMachine, @"SOFTWARE\Policies\Microsoft\OneDrive", "UploadBandwidthLimit",
            "OneDrive maximum upload rate (KB/s).",
            "OneDrive: policy-controlled upload bandwidth limit in KB/s. HKLM policy value; restoring requires elevation.",
            requiresElevation: true),
        Dword("OneDrive download limit", RegistryHive.LocalMachine, @"SOFTWARE\Policies\Microsoft\OneDrive", "DownloadBandwidthLimit",
            "OneDrive maximum download rate (KB/s).",
            "OneDrive: policy-controlled download bandwidth limit in KB/s. HKLM policy value; restoring requires elevation.",
            requiresElevation: true),
        Dword("OneDrive auto upload mgmt", RegistryHive.LocalMachine, @"SOFTWARE\Policies\Microsoft\OneDrive", "EnableAutomaticUploadBandwidthManagement",
            "Let OneDrive auto-manage upload bandwidth.",
            "OneDrive: when enabled OneDrive automatically throttles uploads based on available bandwidth, overriding the fixed upload limit. HKLM policy value; restoring requires elevation.",
            requiresElevation: true),

        // --- Search-index workload throttling ---------------------------------
        Dword("Search indexer back-off", RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Windows Search\Gathering Manager", "DisableBackOff",
            "Stop the indexer from throttling under load.",
            "Search: DisableBackOff keeps the Windows Search Gathering Manager indexing instead of backing off when the machine is busy. HKLM value; restoring requires elevation.",
            requiresElevation: true),
        Dword("Index low-disk pause", RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Windows Search", "PreventIndexingLowDiskSpaceMB",
            "Disk-space threshold (MB) that pauses indexing.",
            "Search: the free-space threshold in MB below which indexing pauses. HKLM value; restoring requires elevation.",
            requiresElevation: true),
        Dword("Index on battery", RegistryHive.LocalMachine, @"SOFTWARE\Policies\Microsoft\Windows\Windows Search", "PreventIndexingOnBattery",
            "Pause search indexing while on battery.",
            "Search: policy that prevents the indexer from running while the device is on battery. HKLM policy value; restoring requires elevation.",
            requiresElevation: true),

        // --- Action Center / notifications ------------------------------------
        Dword("Toast notifications", RegistryHive.CurrentUser, @"SOFTWARE\Microsoft\Windows\CurrentVersion\PushNotifications", "ToastEnabled",
            "Master toast notification switch.",
            "Action Center: master toggle for toast notifications for the current user."),
        Dword("Notification center", RegistryHive.CurrentUser, @"SOFTWARE\Policies\Microsoft\Windows\Explorer", "DisableNotificationCenter",
            "Hide the Action / Notification Center.",
            "Action Center: policy that removes the Notification Center and its taskbar button for the current user."),
        Dword("Global toasts enabled", RegistryHive.CurrentUser, @"SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings", "NOC_GLOBAL_SETTING_TOASTS_ENABLED",
            "Global on/off for all toast banners.",
            "Action Center: global setting that enables or suppresses all toast banners regardless of per-app settings."),

        // --- Visual Studio tweaks ---------------------------------------------
        Dword("VS telemetry opt-out", RegistryHive.CurrentUser, @"SOFTWARE\Microsoft\VisualStudio\Telemetry", "TurnOffSwitch",
            "Opt out of Visual Studio telemetry.",
            "Visual Studio: TurnOffSwitch opts the current user out of VS telemetry collection. Informational; VS also stores this in its private hive.",
            informationalOnly: true),
        Dword("VS feedback dialog", RegistryHive.CurrentUser, @"SOFTWARE\Microsoft\VisualStudio\Feedback", "DisableFeedbackDialog",
            "Suppress the VS feedback prompt.",
            "Visual Studio: DisableFeedbackDialog hides the periodic 'send feedback' prompt. Informational reference value.",
            informationalOnly: true),
        String("VS shared install path", RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\VisualStudio\Setup", "SharedInstallationPath",
            "Shared component install location for VS.",
            "Visual Studio: the SharedInstallationPath used by the VS installer for shared components. Informational; HKLM value, reading may require elevation.",
            informationalOnly: true,
            requiresElevation: true),

        // --- Teams tweaks ------------------------------------------------------
        String("Teams autostart", RegistryHive.CurrentUser, @"SOFTWARE\Microsoft\Windows\CurrentVersion\Run", "com.squirrel.Teams.Teams",
            "Classic Teams auto-start command.",
            "Teams: the Run entry that auto-starts classic Teams at logon. Informational reference value.",
            informationalOnly: true),
        Dword("Teams auto-update", RegistryHive.LocalMachine, @"SOFTWARE\Microsoft\Teams", "disableAutoUpdate",
            "Block Teams from auto-updating.",
            "Teams: disableAutoUpdate prevents the Teams client from updating itself. Informational; HKLM value, restoring may require elevation.",
            informationalOnly: true,
            requiresElevation: true),
        String("Teams machine-wide installer", RegistryHive.LocalMachine, @"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Teams Machine-Wide Installer", "DisplayVersion",
            "Detected Teams machine-wide installer version.",
            "Teams: presence/version of the Teams Machine-Wide Installer. Informational; HKLM value, reading may require elevation.",
            informationalOnly: true,
            requiresElevation: true),

        // --- File-system shadow cache / thumbnail generation ------------------
        Dword("Thumbnails (icons only)", RegistryHive.CurrentUser, @"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "IconsOnly",
            "Show icons instead of generated thumbnails.",
            "Thumbnails: IconsOnly stops Explorer from generating file thumbnails and shows the file-type icon instead."),
        Dword("Network thumbnail cache", RegistryHive.CurrentUser, @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer", "DisableThumbsDBOnNetworkFolders",
            "Disable thumbs.db caches on network folders.",
            "Thumbnails: policy that prevents creation of thumbnail cache (thumbs.db) files on network shares. Informational reference value.",
            informationalOnly: true),
        Dword("Shadow storage min size", RegistryHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\VSS\Settings", "MinDiffAreaFileSize",
            "Minimum Volume Shadow Copy storage size (MB).",
            "Shadow cache: MinDiffAreaFileSize sets the minimum VSS shadow-copy storage area in MB, influencing how often shadow data is recycled. Informational; HKLM value, restoring requires elevation.",
            informationalOnly: true,
            requiresElevation: true),
    ];

    /// <inheritdoc />
    public IReadOnlyList<RegistryDescriptor> GetAll() => _entries;

    private static RegistryDescriptor Dword(
        string name,
        RegistryHive hive,
        string subKeyPath,
        string valueName,
        string shortDescription,
        string fullDescription,
        bool informationalOnly = false,
        bool requiresElevation = false)
        => new()
        {
            Name = name,
            Hive = hive,
            SubKeyPath = subKeyPath,
            ValueName = valueName,
            ValueKind = RegistryValueKind.DWord,
            ShortDescription = shortDescription,
            FullDescription = fullDescription,
            InformationalOnly = informationalOnly,
            RequiresElevation = requiresElevation,
        };

    private static RegistryDescriptor String(
        string name,
        RegistryHive hive,
        string subKeyPath,
        string valueName,
        string shortDescription,
        string fullDescription,
        object? defaultValue = null,
        bool informationalOnly = false,
        bool requiresElevation = false)
        => new()
        {
            Name = name,
            Hive = hive,
            SubKeyPath = subKeyPath,
            ValueName = valueName,
            ValueKind = RegistryValueKind.String,
            ShortDescription = shortDescription,
            FullDescription = fullDescription,
            DefaultValue = defaultValue,
            InformationalOnly = informationalOnly,
            RequiresElevation = requiresElevation,
        };
}
